services:
  llm:
    container_name: llm_service
    env_file:
      - .env
    build:
      context: ./agent
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - ${LLM_PORT}:8000
    networks:
      - tutor-network
    volumes:
      - ./agent/chroma_db:/usr/src/app/chroma_db
      - ./agent/prompts:/usr/src/app/prompts
      - ./agent/uploads:/usr/src/app/uploads
      - ./agent/logs:/usr/src/app/logs

  tutor:
    container_name: tutor_service
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - ${PORTAL_PORT}:3000
    networks:
      - tutor-network
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - tutor-network
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: always

networks:
  tutor-network:
    driver: bridge

volumes:
  mongodb_data: