services:

  frontend:
    container_name: tutor_frontend
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORTAL_PORT}:3001
    networks:
      - tutor-network
  
networks:
  tutor-network:
    driver: bridge
